Fixed MBSIM_SWIG envvar

diff --git a/docker/buildScripts/mbsbd b/docker/buildScripts/mbsbd
--- a/docker/buildScripts/mbsbd
+++ b/docker/buildScripts/mbsbd
@@ -25,8 +25,8 @@ if [ "$BASENAME" == "mbsbd" ]; then
   fi
   
   # check docker
-  if ! sudo docker version > /dev/null; then
-    echo 'Cannot run docker via sudo. Please install and enable docker via sudo for the current user or'
+  if ! docker version > /dev/null; then
+    echo 'Cannot run docker. Please install and enable docker as the current user or'
     echo '(not recommended) run this script as root.'
   fi
   
@@ -62,7 +62,7 @@ if [ "$BASENAME" == "mbsbd" ]; then
   done
   
   # run in mbsimenv/build docker image
-  sudo docker run --rm --user $(id -u):$(id -g) -e HOME=/tmp -v "$MBSIMENVDIR":/mbsim-env -w "$CURDIR" -e MBSIM_SWIG=$MBSIM_SWIG -e DISPLAY -v ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority --net=host mbsimenv/build "${ARGS[@]}"
+  docker run --rm --user $(id -u):$(id -g) -e HOME=/tmp -v "$MBSIMENVDIR":/mbsim-env -w "$CURDIR" -e MBSIM_SWIG=$MBSIM_SWIG -e DISPLAY -v ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority --net=host mbsimenv/build "${ARGS[@]}"
 
 else
   # run via a link
